### ISSUE TITLE
Lighthouse stuck in "Lighthouse is warming up" for lampenwelt.at on Chrome OS

### ISSUE THREAD

**Issue by tomayac** [ChromeDevTools/devtools-frontend#69]
Running a Lighthouse report results in the Audit tab being stuck in "Lighthouse is warming up" state. This is reproducible on two *Chromebooks*, the same report *does work* on Chrome for Mac:

- Environment 1: Chrome OS Version 65.0.3325.167 (Official Build) (beta 64-bit)
- Environment 2: Chrome OS Version 66.0.3359.48 (Offizieller Build) dev (64-Bit)
- Testing site: https://www.lampenwelt.at/

**Comment by tolwin** [comment]
Is it possible, that Lighthouse is not working at all? I.e. not working for any website?
I have tested:
- https://www.nytimes.com/
- https://www.cnn.com/
- https://www.google.de

and all I see is the "Lighthouse is warming up...." message box.

**Comment by floric** [comment]
Same happens for me with:
* Env: 65.0.3325.181 (Official Build) Built on Ubuntu , running on LinuxMint 18.1 (64-bit)

I tried with all five modes as well as only using Permance or SEO. All seem to be stuck.

**Comment by tomayac** [comment]
Yay! This seems to have been fixed in Version 66.0.3359.79 (Official Build) beta (64-bit). Closing for now.

**Comment by vanWittlaer** [comment]
Nah, still hanging in Version 66.0.3359.81 (Entwickler-Build) Ubuntu 16.04 (64-Bit) - plse re-open

**Comment by pratikborsadiya** [comment]
This issue still persists in Version 66.0.3359.139 on Ubuntu 18.04.

**Comment by magro** [comment]
Same here, on Fedora 27, chromium-65.0.3325.181-1.fc27.x86_64

**Comment by jordanade** [comment]
Same here, on macOS 10.13.4, chromium 66.0.3359.117

**Comment by jlndk** [comment]
Same here, on Ubuntu 17.10 artful (64-bit), chromium version 66.0.3359.139 (Official Build)

**Comment by vernjan** [comment]
Same here: Version 66.0.3359.139 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by VinnyFonseca** [comment]
Same here: Version 66.0.3359.139 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Comment by CRidge** [comment]
I had an issue where this happened some of the time. For me the fix was to make sure the page was in the full desktop view when starting the audit. If I had chosen a mobile enumlation view, it got stuck.

**Comment by patrickallaert** [comment]
I was able to reproduce it on Gentoo Linux with versions 66.0.3359.139 and 66.0.3359.170.
However, using version 67.0.3396.40 seems to fix it!

**Comment by brianlmerritt-kent** [comment]
Ubuntu 18.04 also has the same issue (and fail to cancel) on 66.0.3359.181.

When I checked with the colleague who showed me the audit, his was working because he was using Chrome 67 rather than Chromium.

**Comment by fattypiggy** [comment]
same here!
OS: OSX10.13.5
Chrome: 67

**Comment by Dmole** [comment]
Chromium/66 on Ubuntu 18.04 LTS is so buggy :( Please backport the fix and notify the maintaner.

**Comment by tyler36** [comment]
Updated to Chrome Version 68.0.3440.75 (Official Build) (64-bit) this morning.
Started having same issue.

OS: Win10 x64

**Comment by morgunkorn** [comment]
Detail of the error thrown by Lighthouse 3.0 during the warming up:

```
Uncaught (in promise) SyntaxError: Unexpected number
    at eval (<anonymous>)
    at evaluateScript (audits2_worker.js?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@cf598d63a4f1b9e7cd14f2a8433276b196e3e07d/:23)
    at scriptSourceLoaded (audits2_worker.js?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@cf598d63a4f1b9e7cd14f2a8433276b196e3e07d/:21)
audits2_worker.js?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@cf598d63a4f1b…:1 Uncaught (in promise) SyntaxError: Unexpected number
```

The error occurs when the function evaluateScript() is run, it seems the script source contains an http error 404 

```javascript
function scriptSourceLoaded(scriptNumber, scriptSource) {
	sources[scriptNumber] = scriptSource || '';
	while (typeof sources[scriptToEval] !== 'undefined') {
		evaluateScript(urls[scriptToEval], sources[scriptToEval]);
		++scriptToEval;
	}
}
```

**Comment by tyler36** [comment]
Tested again this morning. Works as expected. 

If @morgunkorn was right about a 404 issues, I assume this asset now exists, thus problem is no more!

**Comment by Dmole** [comment]
Still busted on Ubuntu.

**Comment by patrickhulce** [comment]
@Dmole Chromium on linux is a separate issue that should be fixed in 69.0.3456.0

**Comment by Areahints** [comment]
@Dmole @patrickhulce any link to download 69.0.3456.0 yet?

**Comment by Dmole** [comment]
@Areahints Yes, Lighthouse works in the now avalable "Version 68.0.3440.75 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)"

**Comment by Areahints** [comment]
I updated yesterday, still no luck, hangs on run
Version 68.0.3440.75 (official build) built on Ubuntu, running on Zorn 12
(64 bit)

**Comment by Areahints** [comment]
It doesn't require internet to run right? I'm offline on the workstation.
That can't be a problem, I'm updating my other pc and will report on this

**Comment by Areahints** [comment]
lighthouse now working perfectly! thanks

**Comment by mfkvfn** [comment]
not working in Chrome 68.0.3440.106, 64 bit,windows 10
but work correctly in Chrome extendsions 'Lighthouse'

**Comment by mafshin** [comment]
Same issue here

Chrome: 71.0.3578.98
Windows 6.1.7601 64bit

**Comment by soft-angel** [comment]
I still have the issue:
Версия 72.0.3626.96 (Официальная сборка), snap (64 бит)
ubuntu 18.04 -

**Comment by harry-liu** [comment]
I still have the issue:
Chrome: Version 72.0.3626.121 (Official Build) (64-bit)
OS: MacOS

**Comment by rpetty** [comment]
I have the issue when I try to launch Lighthouse from "Developers Tools".  It works if I click the Lighthouse Chrome extension.
Brave: Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
OS: MacOS 10.14.4 (18E226)

**Comment by HazCod** [comment]
Same for latest brave on ironpeak.be

**Comment by leifniem** [comment]
Same for every website.

**Comment by minaairsupport** [comment]
the same here for all site 

Google Chrome | 75.0.3770.142 (Official Build) (64-bit)

**Comment by ChrisGitIt** [comment]
Same issue here with 76.0.3809.100 Mac.

For some sites, it seems to work. On my current work in progress site, a "debugger;" command within JS source seem to brake the lighthouse test. Looks like its trying to jump to the source => debugger line, but is unable to do so. The previous version was jumping to the source tab while running lighthouse. There I could just "skip" the debugger line and lighthouse finished its job.
